security:
    enable_authenticator_manager: true
    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        main:
            custom_authenticators:
                - App\Authenticator\TokenAuthenticator
    access_control:
        - { path: '^/job', methods: [GET], roles: PUBLIC_ACCESS }
        - { path: '^/job', methods: [POST], roles: IS_AUTHENTICATED_REMEMBERED }

