version: '3'

services:
  app:
    container_name: app.talentify
    env_file:
      - ./app/.env
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        APP_STAGE: "dev"
    volumes:
      - ./app:/app
    networks:
      - bubble

  db:
    container_name: db.talentify
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talentify
    ports:
      - 33060:3306
    volumes:
      - ./.docker/database:/var/lib/mysql
    networks:
      - bubble

  api:
    container_name: api.talentify
    image: nginx:1.19.2-alpine
    depends_on:
      - app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker/config/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - "9145:80"
      - "443:443"
    networks:
      - bubble

networks:
  bubble:
