version: '3'
services:
    nginx:
        container_name: tay_nginx
        restart: always
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/www
            - ./.nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.env.example:/www/.env
        links:
            - php
        networks:
            - server_network
    php:
        container_name: tay_php
        build: .
        volumes:
            - ./:/www
        networks:
            - server_network
    mysql:
        container_name: tay_mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "talentify2020"
            MYSQL_DATABASE: "talentify"
        ports:
            - "3306:3306"
        volumes:
            - ./.mysql:/var/lib/mysql
        networks:
            - server_network
networks:
    server_network:
        driver: bridge
