version: "3"
services:
    web:
      build: .
      ports:
        - "8001:80"
      volumes:
        - "./:/var/www/html:cached"
      links:
        - mysql
      depends_on:
        - mysql
      networks:
        - talentify-network
    mysql:
      image: mysql:5.7.22
      tty: true
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: talentify
        MYSQL_ROOT_PASSWORD: "admin@123"
      volumes:
        - dbdata:/var/lib/mysql/
        - ./my.cnf:/etc/mysql/my.cnf
      networks:
        - talentify-network
volumes:
  dbdata:
    driver: local
networks:
  talentify-network:
    driver: bridge
    

