version: '3'
services:
  talentify-php:
      container_name: talentify-php
      build:
        dockerfile: devops/php-fpm/Dockerfile
        context: .
      volumes:
        - ./backend:/var/www/html
        - ./devops/php-fpm/dist/php.ini:/usr/local/etc/php/conf.d/php.ini
      working_dir: /var/www/html

  talentify-web:
      container_name: talentify-web
      image: nginx:alpine
      ports:
          - 9000:80
      volumes:
          - ./backend:/var/www/html
          - ./devops/nginx/default.conf:/etc/nginx/conf.d/default.conf

  talentify-mysql-db:
    image: mysql:5.7.26
    container_name: talentify-mysql-db
    volumes:
        - ./infra/data/mysql:/var/lib/mysql:cached
    environment:
        - MYSQL_ROOT_PASSWORD=dev123
        - MYSQL_DATABASE=myapp
    ports:
        - 3306:3306
