version: '3.3'

volumes:
  talentify-database:
    external: true

networks:
  talentify:
    external: true

services:
  db:
    image: mysql:5.7
    volumes:
      - talentify-database:/var/lib/mysql
    ports:
      - '33046:3306'
    environment:
      - 'MYSQL_DATABASE=talentify'
      - 'MYSQL_USER=homestead'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
    networks:
      - talentify
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - '.:/var/www'
    ports:
      - '3040:80'
    networks:
      - talentify
    depends_on:
      - db
