version: '3'
services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    image: aironou/talentify:php7.4
    volumes:
      - .:/aironou
  local-server:
    image: aironou/talentify:php7.4
    command: symfony local:server:start
    container_name: aironou-talentify-local-server
    volumes:
      - .:/aironou
    env_file:
      - .env.local
    ports:
      - "${LOCAL_SERVER_HOST_PORT}:8000"
  test:
    image: aironou/talentify:php7.4
    command: php vendor/bin/phpunit --testdox --coverage-text
    container_name: aironou-talentify-test
    volumes:
      - .:/aironou
    env_file:
      - .env.test.local