version: '3'
services:
  talentify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentify-api
    environment:
        APP_NAME: 'talentify'
        DEBUG: 'false'
        APP_ENCODING: 'UTF-8'
        APP_DEFAULT_LOCALE: 'en_US'
        APP_DEFAULT_TIMEZONE: 'UTC'
        SECURITY_SALT : 'a1agSUz3sUoamFPQB05MAMhFokOSydON91'
        DB_HOST: 'mysql'
        DB_PORT: '3306'
        DB_DATABASE: 'talentify'
        DB_USERNAME: 'talentify'
        DB_PASSWORD: '123456'
#    volumes:
#      - .:/var/www/html/
    networks:
      - cakephp4     
    ports:
      - 8080:80
  mysql:
    image: 'mysql:8.0'
    container_name: talentify-database
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: 'talentify'
        MYSQL_USER: 'talentify'
        MYSQL_PASSWORD: '123456'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'volumemysql:/var/lib/mysql'
    networks:
        - cakephp4
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
networks:
    cakephp4:
        driver: bridge
volumes:
    volumemysql:
        driver: local