-- MySQL Script generated by MySQL Workbench
-- qua 01 jul 2020 22:45:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chp0a2jww2pha8pn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chp0a2jww2pha8pn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chp0a2jww2pha8pn` DEFAULT CHARACTER SET utf8 ;
USE `chp0a2jww2pha8pn` ;

-- -----------------------------------------------------
-- Table `chp0a2jww2pha8pn`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chp0a2jww2pha8pn`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chp0a2jww2pha8pn`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chp0a2jww2pha8pn`.`form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_form_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_form_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `chp0a2jww2pha8pn`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chp0a2jww2pha8pn`.`fieldtype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chp0a2jww2pha8pn`.`fieldtype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chp0a2jww2pha8pn`.`field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chp0a2jww2pha8pn`.`field` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `premisse` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `form_id` INT NOT NULL,
  `fieldtype_id` INT NOT NULL,
  PRIMARY KEY (`id`, `form_id`, `fieldtype_id`),
  INDEX `fk_field_form_idx` (`form_id` ASC) ,
  INDEX `fk_field_fieldtype1_idx` (`fieldtype_id` ASC) ,
  CONSTRAINT `fk_field_form`
    FOREIGN KEY (`form_id`)
    REFERENCES `chp0a2jww2pha8pn`.`form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_fieldtype1`
    FOREIGN KEY (`fieldtype_id`)
    REFERENCES `chp0a2jww2pha8pn`.`fieldtype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chp0a2jww2pha8pn`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chp0a2jww2pha8pn`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `field_id` INT NOT NULL,
  PRIMARY KEY (`id`, `field_id`),
  INDEX `fk_answer_field1_idx` (`field_id` ASC) ,
  CONSTRAINT `fk_answer_field1`
    FOREIGN KEY (`field_id`)
    REFERENCES `chp0a2jww2pha8pn`.`field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chp0a2jww2pha8pn`.`alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chp0a2jww2pha8pn`.`alternative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `field_id` INT NOT NULL,
  PRIMARY KEY (`id`, `field_id`),
  INDEX `fk_alternative_field1_idx` (`field_id` ASC) ,
  CONSTRAINT `fk_alternative_field1`
    FOREIGN KEY (`field_id`)
    REFERENCES `chp0a2jww2pha8pn`.`field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
