index:
    path: /
    controller: App\Controller\DefaultController::index

create_job:
    path: /admin/jobs/create
    methods: [GET]
    controller: App\Controller\JobController::create

create_job_success:
    path: /admin/jobs/create-sucess
    methods: [GET]
    controller: App\Controller\JobController::createSuccess

save_job:
    path: /admin/jobs/create
    methods: [POST]
    controller: App\Controller\JobController::save

############### API ROUTES ###############
api_job_list_opened:
    path: /api/jobs
    methods: [GET]
    controller: App\Controller\Rest\JobController::listOpenedJobs

api_job_create:
    path: /api/jobs
    methods: [POST]
    controller: App\Controller\Rest\JobController::save