<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9bBx3c4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9bBx3c4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9bBx3c4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9bBx3c4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9bBx3c4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9bBx3c4',
    'container.build_id' => 'a6676773',
    'container.build_time' => 1611072783,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9bBx3c4');
