<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'job_confirme_delete' => [['job'], ['_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\ConfirmeDeleteAction'], [], [['text', '/confirme/delete'], ['variable', '/', '[^/]++', 'job'], ['text', '/admin/jobs']], [], []],
    'job_delete' => [['job'], ['_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\DeleteAction'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'job'], ['text', '/admin/jobs']], [], []],
    'job_new' => [[], ['_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\FormAction'], [], [['text', '/admin/jobs/new']], [], []],
    'job_edit' => [['job'], ['job' => null, '_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\FormAction'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'job'], ['text', '/admin/jobs']], [], []],
    'jobs_list' => [[], ['_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\ListAction'], [], [['text', '/admin/jobs']], [], []],
    'jobs_list_page' => [['page'], ['page' => null, '_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\ListAction'], [], [['variable', '/', '[^/]++', 'page'], ['text', '/admin/jobs/page']], [], []],
    'jobs_list_status' => [['status'], ['status' => null, '_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\ListAction'], [], [['variable', '/', '[^/]++', 'status'], ['text', '/admin/jobs/status']], [], []],
    'jobs_list_status_page' => [['status', 'page'], ['status' => null, 'page' => null, '_controller' => 'App\\Infrastructure\\Action\\Admin\\Jobs\\ListAction'], [], [['variable', '/', '[^/]++', 'page'], ['text', '/page'], ['variable', '/', '[^/]++', 'status'], ['text', '/admin/jobs/status']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Infrastructure\\Action\\Admin\\LogoutAction::logout'], [], [['text', '/logout']], [], []],
    'home' => [[], ['_controller' => 'App\\Infrastructure\\Action\\HomeAction'], [], [['text', '/']], [], []],
    'home_page' => [['page'], ['page' => null, '_controller' => 'App\\Infrastructure\\Action\\HomeAction'], [], [['variable', '/', '[^/]++', 'page'], ['text', '/page']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Infrastructure\\Action\\LoginAction'], [], [['text', '/login']], [], []],
];
